[package]
name = "leakred"
version = "0.1.0"
description = "Leakred — tải video/ảnh từ TikTok, Instagram, Facebook"
authors = ["leakdev0410"]
edition = "2021"
rust-version = "1.77"

[lib]
name = "leakred_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "fs", "io-util"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls-webpki-roots", "json", "gzip", "brotli", "stream"] }
futures-util = "0.3"
scraper = "0.20"
regex = "1"
url = "2"
urlencoding = "2"
once_cell = "1"
anyhow = "1"
thiserror = "1"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
